title: Christopher Klamm
url: https://klamm.info
baseurl: ''

markdown: kramdown

tracking_id: #

#footer: yes
#footer_url: "https://ankitsultana.com"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: gitPage/resume.pdf
 - name: "Contact"
   link: gitPage/contact.md
 - name: "Blog"
   link: gitPage/blog.html

theme: jekyll-theme-cayman
