title: Christopher Klamm
url: https://klamm.info

markdown: kramdown

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "News"
#   link: "news"
# - name: "Projects"
#   link: "projects"
# - name: "Qualifications"
#   link: "talks"
 - name: "Publications"
   link: "publication"
 - name: "Teaching"
   link: "teaching"
 - name: "CV"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
# - name: "Blog"
#   link: "blog.html"

theme: jekyll-theme-cayman
