title: Christopher Klamm
url: https://klamm.info

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://ankitsultana.com"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: /resume.pdf
 - name: "Contact"
   link: /contact.md
 - name: "Blog"
   link: /blog.html

theme: jekyll-theme-cayman
